import { Inter } from "next/font/google";
import "@styles/globals.css";
import NavBar from "@/Components/NavBar";
import Footer from "@/Components/Footer";

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <div className={inter.className}>
      <NavBar />
      {children}
      <Footer />
    </div>
  );
}
