import"@/styles/globals.css";

export const metadata = {
  title: "Top Placemnet",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <div >
      {children}
    </div>
  );
}
